### ISSUE TITLE
Action fail when plugin is incompatible and `fail-if-incompatible` set to 'no'

### ISSUE THREAD

**Issue by mikhail-vl** [grafana/plugin-actions#2]
Action is set as described in the documentation with `fail-if-incompatible` set to `no`:
```
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@v1
        with:
          module: "./src/module.ts"
          comment-pr: 'yes'
          fail-if-incompatible: 'no'
```

  Here is the output:
```
./src/module.ts is not fully compatible with @grafana/data,@grafana/ui,@grafana/runtime,@grafana/schema,@grafana/e2e-selectors,@grafana/experimental

--step reference removed--
Please read over the compatibility report above and update possible issues.
--step reference removed--

--step reference removed--
If you think the compatibility issues are not a problem (e.g. only type changes), it is adviced to update the target list of packages to their latest version in your project.
--step reference removed--
Error: Process completed with exit code 1.
```

  Looking at the action's code, it makes sense to fail when `fail-if-incompatible` is set to `yes`:

```
- if: inputs.fail-if-incompatible == 'yes' && steps.run-levitate.outputs.code == 1
      run: |
        echo "Possible incompatibilities found. Check Levitate output for further information"
        exit 1
      shell: "bash"
```

  Should the action clear out the exit code if `fail-if-incompatible` set to `no`?
