### ISSUE TITLE
Can I add have a repo of multiple plugins and use github action in subdirectories?

### ISSUE THREAD

**Issue by mehr74** [grafana/plugin-actions#34]
The following Github action from plugin fails, when I use subdirectory to build multiple plugins.

```yaml
  resolve-versions:
    name: Resolve e2e images
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: build
    if: ${{ needs.build.outputs.has-e2e == 'true' }}
    outputs:
      matrix: ${{ steps.resolve-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve Grafana E2E versions
        id: resolve-versions
        uses: grafana/plugin-actions/e2e-version@main
```
With the following error.

```
Error: ENOENT: no such file or directory, open '/home/runner/work/xxx/xxx/src/plugin.json'
```
